# Generated by Django 5.2.12 on 2026-05-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('cd_marca', models.AutoField(primary_key=True, serialize=False)),
                ('ds_marca', models.CharField()),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
