# Generated by Django 5.2.12 on 2026-05-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mat_med', '0001_initial'),
        ('pessoa_juridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('nr_negociacao', models.IntegerField(primary_key=True, serialize=False)),
                ('obs_negocia', models.CharField()),
                ('qtd_matmed', models.IntegerField()),
                ('cd_mat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='negociacoes', to='mat_med.matmed')),
                ('cd_negociador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='negociacoes_as_negociador', to='pessoa_juridica.pessoajuridica')),
                ('cd_negociante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='negociacoes_as_negociante', to='pessoa_juridica.pessoajuridica')),
            ],
        ),
    ]
