# Generated by Django 5.2.12 on 2026-05-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabricante', '__first__'),
        ('mat_med', '__first__'),
        ('pessoa_juridica', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('nr_lote', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_fabricacao', models.DateTimeField()),
                ('dt_validade', models.DateField()),
                ('qtd_lote', models.IntegerField()),
                ('unidade_med', models.CharField(max_length=20)),
                ('cd_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lotes', to='mat_med.matmed')),
                ('cd_pessoaj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pessoas_jur', to='pessoa_juridica.pessoajuridica')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lotes', to='fabricante.fabricante')),
            ],
        ),
    ]
