# Generated by Django 5.2.12 on 2026-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_lote_ie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='ds_lote',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
