# Generated by Django 5.2.12 on 2026-05-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('cd_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('ds_fabricante', models.CharField(max_length=255)),
                ('cnpj_fabri', models.CharField(max_length=18, unique=True)),
            ],
        ),
    ]
