# Generated by Django 5.2.12 on 2026-05-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negociacao', '0001_initial'),
        ('pessoa_juridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('cd_msg', models.AutoField(primary_key=True, serialize=False)),
                ('dt_registro', models.DateTimeField(auto_now_add=True)),
                ('ds_msg', models.CharField()),
                ('cd_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mensagens_recebidas', to='pessoa_juridica.pessoajuridica')),
                ('cd_negociacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mensagens', to='negociacao.negociacao')),
                ('cd_remetente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mensagens_enviadas', to='pessoa_juridica.pessoajuridica')),
            ],
        ),
    ]
