# Generated by Django 5.2.12 on 2026-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('cd_plano', models.IntegerField(primary_key=True, serialize=False)),
                ('ds_plano', models.CharField()),
                ('val_plano', models.FloatField()),
            ],
        ),
    ]
