# Generated by Django 5.2.12 on 2026-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cd_fornecedor', models.IntegerField(primary_key=True, serialize=False)),
                ('ds_fornecedor', models.CharField(max_length=255)),
                ('cnpj_fornc', models.IntegerField()),
            ],
        ),
    ]
