# Generated by Django 5.2.12 on 2026-05-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('mat_med', '0001_initial'),
        ('pessoa_juridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('nr_lote', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_fabricacao', models.DateTimeField()),
                ('dt_validade', models.DateField()),
                ('qtd_lote', models.IntegerField()),
                ('unidade_med', models.CharField(max_length=20)),
                ('cd_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lotes', to='mat_med.matmed')),
                ('cd_pessoaj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pessoas_jur', to='pessoa_juridica.pessoajuridica')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lotes', to='fornecedor.fornecedor')),
            ],
        ),
    ]
