# Generated by Django 5.2.12 on 2026-05-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='ds_lote',
            field=models.CharField(default='Sem descricao', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='ie_status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
