# Generated by Django 5.2.12 on 2026-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_lote_ds_lote_lote_ie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='nr_lote',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
