# Generated by Django 5.2.12 on 2026-05-19 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
        ('mat_med', '0001_initial'),
        ('pessoa_juridica', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('nr_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_mat', models.IntegerField()),
                ('val_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ds_obs', models.CharField(blank=True, default='', max_length=500)),
                ('data_anuncio', models.DateField()),
                ('ie_status', models.CharField(choices=[('A', 'ATIVO'), ('I', 'INATIVO'), ('F', 'FINALIZADO'), ('E', 'EXPIRADO')], default='A', max_length=1)),
                ('cd_mat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='mat_med.matmed')),
                ('cd_pessoa_anunciante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='pessoa_juridica.pessoajuridica')),
                ('nr_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='lote.lote')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
    ]
