# Generated by Django 5.2.12 on 2026-05-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='ds_obs',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='nr_lote',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='data_anuncio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ie_status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='qtd_mat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
