# Generated by Django 5.2.12 on 2026-05-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_remove_anuncio_ds_obs_remove_anuncio_nr_lote_and_more'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anúncios'},
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ds_obs',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='nr_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios', to='lote.lote'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='qtd_mat',
            field=models.IntegerField(),
        ),
    ]
