# Generated by Django 5.2.12 on 2026-05-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0004_alter_anuncio_data_anuncio_alter_anuncio_ds_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='data_anuncio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
