# Generated by Django 5.2.12 on 2026-05-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0006_anuncio_cd_pessoa_compradora_anuncio_val_aceito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='val_unitario',
        ),
    ]
