# Generated by Django 5.2.12 on 2026-05-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marcas', '0001_initial'),
        ('pessoa_juridica', '__first__'),
        ('tipo_matmed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatMed',
            fields=[
                ('cd_mat', models.AutoField(primary_key=True, serialize=False)),
                ('ds_mat', models.CharField()),
                ('ds_marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materiais', to='marcas.marcas')),
                ('ds_pessoaj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materiais', to='pessoa_juridica.pessoajuridica')),
                ('ds_tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materiais', to='tipo_matmed.tipomatmed')),
            ],
        ),
    ]
