# Generated by Django 5.2.12 on 2026-06-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matmed',
            name='cd_brasindice',
            field=models.CharField(blank=True, help_text='Referência de preço de medicamentos, define PF (Preço de Fábrica) e PMC (Preço Máximo ao Consumidor) — ex: 41723412ERRU', max_length=15, null=True, verbose_name='Código Brasíndice'),
        ),
        migrations.AddField(
            model_name='matmed',
            name='cd_simpro',
            field=models.CharField(blank=True, help_text='Referência de preço de materiais hospitalares (compras, faturamento, auditoria) — ex: 1197898', max_length=10, null=True, verbose_name='Código Simpro'),
        ),
        migrations.AddField(
            model_name='matmed',
            name='cd_tiss',
            field=models.CharField(blank=True, help_text='Padrão de comunicação, número que representa a tabela de origem (ex: 19 = Brasíndice, 20 = TUSS)', max_length=2, null=True, verbose_name='Código TISS'),
        ),
        migrations.AddField(
            model_name='matmed',
            name='cd_tuss',
            field=models.CharField(blank=True, help_text='"CPF" do material/medicamento no sistema de saúde suplementar (ANS) — 8 dígitos (ex: 70908788)', max_length=10, null=True, verbose_name='Código TUSS'),
        ),
    ]
