# Generated by Django 5.2.12 on 2026-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat_med', '0002_matmed_cd_brasindice_matmed_cd_simpro_matmed_cd_tiss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matmed',
            name='cd_brasindice',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Brasíndice'),
        ),
        migrations.AlterField(
            model_name='matmed',
            name='cd_simpro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código SIMPRO'),
        ),
        migrations.AlterField(
            model_name='matmed',
            name='cd_tiss',
            field=models.CharField(blank=True, choices=[('19', 'Brasíndice'), ('20', 'TUSS')], max_length=2, null=True, verbose_name='Tabela TISS'),
        ),
        migrations.AlterField(
            model_name='matmed',
            name='cd_tuss',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código TUSS'),
        ),
        migrations.AlterField(
            model_name='matmed',
            name='ds_mat',
            field=models.CharField(max_length=255),
        ),
    ]
