# Generated by Django 5.2.12 on 2026-05-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMatMed',
            fields=[
                ('cd_tipo', models.CharField(choices=[('MD01', 'MD01'), ('MT01', 'MT01'), ('PD01', 'PD01')], max_length=10, primary_key=True, serialize=False)),
                ('ds_tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
