# Generated by Django 5.2.12 on 2026-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_matmed', '0002_alter_tipomatmed_cd_tipo_alter_tipomatmed_ds_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomatmed',
            name='cd_tipo',
            field=models.CharField(choices=[('MD01', 'MD01'), ('MT01', 'MT01'), ('PD01', 'PD01')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
