# Generated by Django 5.2.12 on 2026-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('cd_pessoaj', models.AutoField(primary_key=True, serialize=False)),
                ('nm_pessoaj', models.CharField()),
                ('email_pj', models.CharField()),
                ('senha_pj', models.CharField()),
                ('resp_tec', models.CharField()),
                ('nr_cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField()),
            ],
        ),
    ]
