# Generated by Django 5.2.12 on 2026-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_juridica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('BLOQUEADA', 'Bloqueada')], default='PENDENTE', max_length=20),
        ),
    ]
