# Generated by Django 5.2.12 on 2026-05-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('cd_pessoaj', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_pessoaj', models.CharField()),
                ('email_pj', models.CharField()),
                ('senha_pj', models.CharField()),
                ('resp_tec', models.CharField()),
                ('nr_cnpj', models.IntegerField()),
                ('razao_social', models.CharField()),
                ('ds_plano', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pessoas_jur', to='plano.plano')),
            ],
        ),
    ]
