# Generated by Django 5.2.12 on 2026-05-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_matmed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomatmed',
            name='cd_tipo',
            field=models.CharField(choices=[('MD01', 'MEDICAMENTO'), ('MT01', 'MATERIAL'), ('PD01', 'PRODUTO')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipomatmed',
            name='ds_tipo',
            field=models.CharField(max_length=50),
        ),
    ]
