# Generated by Django 5.2.12 on 2026-05-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_alter_anuncio_options_anuncio_ds_obs_anuncio_nr_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='data_anuncio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ds_obs',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
