# Generated by Django 5.2.12 on 2026-05-27 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0005_alter_anuncio_data_anuncio'),
        ('pessoa_juridica', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='cd_pessoa_compradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='anuncios_comprados', to='pessoa_juridica.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='val_aceito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='val_proposta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='ie_status',
            field=models.CharField(choices=[('A', 'Ativo'), ('N', 'Em Negociação'), ('F', 'Finalizado'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
