# Generated by Django 5.2.12 on 2026-05-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0007_remove_anuncio_val_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='val_base',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
