# Generated by Django 5.2.12 on 2026-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_fornc',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
